layout: 
  ortho_layout:
    rows: 4
    columns: 3
layers:
  default:
  - ['SYMBOLS .,?!', 'UP ABC', 'DEF']
  - ['LEFT GHI', 'DOWN JKL', 'RIGHT MNO']
  - ['PQRS', 'TAB TUV', 'WXYZ']
  - - {t: BACKSPACE, h: DELETE}
    - SPACE
    - {t: ., h: ENTER}
  symbols:
  - ['!', '@', '#']
  - [':', '%', ^]
  - ['&', '*', '?']
  - ['-', _, '=']
  gaming:
  - - {t: '1', h: '4'}
    - {t: '2', h: '5'}
    - {t: '3', h: '6'}
  - - {t: Q, h: R}
    - W
    - {t: E, h: T}
  - [A, S, D]
  - - {t: Z, h: LCTRL}
    - {t: X, h: SPACE}
    - {t: C, h: LALT}
  numbers:
  - [7, 8, 9]
  - [4, 5, 6]
  - [1, 2, 3]
  - - {t: 0, h: LCTRL}
    - {t: ',', h: LALT}
    - {t: ., h: RCTRL}
combos:
- p: [9, 10, 11]
  k: {t: gaming, h: toggle}
  l: [default]
- p: [6, 7, 8]
  k: {t: symbols, h: toggle}
  l: [default]
- p: [3, 4, 5]
  k: {t: numbers, h: toggle}
  l: [default]
- p: [9, 10, 11]
  k: {t: default, h: toggle}
  l: [symbols, gaming, numbers]
- p: [0, 1, 2]
  k: BT CLR ALL
  l: [symbols]
- p: [0, 1]
  k: BT PREV
  l: [symbols]
- p: [1, 2]
  k: BT NEXT
  l: [symbols]
- p: [0, 2]
  k: OUT TOG
  l: [symbols]
