[keyboard]
name = "pipar_chip_isp1807"
product_name = "Pipar Chip"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "Pipar"
chip = "nrf52840"

[matrix]
input_pins = ["P1_02", "P1_06", "P1_15"]
output_pins = ["P1_14", "P1_13", "P1_05", "P1_08"]
row2col = false # using col2row

[layout]
rows = 3
cols = 4
layers = 1
keymap = [
    [
        ["A", "B", "C", "D"],
        ["E", "F", "G", "BacklightToggle"],
        ["I", "J", "K", "CapsLock"],
    ],
]

[storage]
clear_storage = true

[light]
capslock = { pin = "P1_00", low_active = false }

[backlight]
backlight = { pin = "P1_09", low_active = true}

[ble]
enabled = true
# vddh has an internal voltage divider
battery_adc_pin = "vddh"
# Or
# battery_adc_pin = "P0_04"
# adc_divider_measured = 2000
# adc_divider_total = 2806

# charge_state.pin = "P0_25"
# charge_state.low_active = false
# charge_led.pin = "P0_29"
# charge_led.low_active = false
