
---
include:
  # Pipar Point
  - board: pipar_point_left
  - board: pipar_point_right
  - board: pipar_point_right
    shield: settings_reset
  # Pipar Chip
  - board: pipar_chip
  # Pipar Sool  
  - board: xiao_ble
    shield: pipar_sool_dongle
    snippet: studio-rpc-usb-uart
  # - board: xiao_ble
  #   shield: pipar_sool_central
  #   snippet: studio-rpc-usb-uart
  - board: xiao_ble
    shield: pipar_sool_left
  - board: xiao_ble
    shield: pipar_sool_right
  - board: xiao_ble
    shield: settings_reset
  # Pipar Flake
  - board: nice_nano
    shield: pipar_flake
  - board: nice_nano
    shield: settings_reset
