file_format: "1"
id: pipar_point
name: Pipar Point
url: https://github.com/rasmuskoit/pipar
type: board
arch: arm
features:
  - keys
  - studio
  - backlight
outputs:
  - usb
  - ble
siblings:
  - pipar_point_left
  - pipar_point_right