identifier: pipar_point
name: Pipar Point
url: https://github.com/rasmuskoit/pipar
type: mcu
arch: arm
toolchain:
  - zephyr
  - gnuarmemb
  - xtools
supported:
  - adc
  - usb_device
  - ble
  - ieee802154
  - pwm
  - watchdog
  - gpio
  - i2c
  - spi
